--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend.lua"
local CreatePositionFrame = luaExtend.CreatePositionFrame
local CreateVisibleFrame = luaExtend.CreateVisibleFrame
local CreateColorFrame = luaExtend.CreateColorFrame
local CreateEventFrame = luaExtend.CreateEventFrame
local CreateInnerActionFrame = luaExtend.CreateInnerActionFrame
local CreateAlphaFrame = luaExtend.CreateAlphaFrame
local CreateZOrderFrame = luaExtend.CreateZOrderFrame
local CreateScaleFrame = luaExtend.CreateScaleFrame
local CreateRotationSkewFrame = luaExtend.CreateRotationSkewFrame
local CreateAnchorPointFrame = luaExtend.CreateAnchorPointFrame
local CreateTextureFrame = luaExtend.CreateTextureFrame

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()  
Scene:setName("Scene")
Scene:setPosition(0, 0)
Scene:setScaleX(1)
Scene:setScaleY(1)
Scene:setLocalZOrder(0)
Scene:setAnchorPoint(0, 0)
Scene:setOpacity(255)
Scene:setColor(cc.c3b(255, 255, 255))
Scene:setVisible(true)
Scene:setRotation(0)
Scene:setRotationSkewX(0)
Scene:setRotationSkewY(0)
Scene:setTag(0)
Scene:setCascadeColorEnabled(true)
Scene:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Scene)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(640, 960))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0)
layout:setRightMargin(0)
layout:setTopMargin(0)
layout:setBottomMargin(0)

--Create Sprite_1
local Sprite_1 = cc.Sprite:create("images/athena/change_n.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setPosition(191.7, 679)
Sprite_1:setScaleX(1)
Sprite_1:setScaleY(1)
Sprite_1:setLocalZOrder(0)
Sprite_1:setAnchorPoint(0.4, 0.5)
Sprite_1:setOpacity(255)
Sprite_1:setColor(cc.c3b(255, 255, 255))
Sprite_1:setVisible(true)
Sprite_1:setRotation(0)
Sprite_1:setRotationSkewX(0)
Sprite_1:setRotationSkewY(0)
Sprite_1:setTag(4)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.2995313)
layout:setPositionPercentY(0.7072917)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(103, 84))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(150.5)
layout:setRightMargin(386.5)
layout:setTopMargin(239)
layout:setBottomMargin(637)
Sprite_1:setFlippedX(false)
Sprite_1:setFlippedY(false)
Scene:addChild(Sprite_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

